apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podchaoses.chaos.gopherconbr.org
spec:
  group: chaos.gopherconbr.org
  names:
    kind: PodChaos
    listKind: PodChaosList
    plural: podchaoses
    singular: podchaos
  scope: Namespaced
  version: v1beta1
